[package]
name = "typhoondsl-outliner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustemo = { version = "0.1.0", path = "../../../rust/rustemo/rustemo" }
regex = "1"
colored = "2"
